services:
  nuclei-scan:
    image: projectdiscovery/nuclei:latest
    volumes:
      # - ./webgoat/:/templates/
      - ./waf-templates/:/templates/
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["./entrypoint.sh"]
    environment:
      WORKFLOW: "${WORKFLOW?}"
      TARGET: "${TARGET?}"
      HEADER_WAF_BYPASS: "${HEADER_WAF_BYPASS-}"
      DEBUG: "${DEBUG-0}"
