apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: juice-shop

resources:
  # - external-secrets/
  - ./juice-shop/
  # - waf-association/
patches:
  - path: ./patches/ingress-waf-patch.yaml
