apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - external-secrets/
  - ./juice-shop/
  - ./webgoat/
  # - waf-association/
patches:
  - target: 
      group: networking.k8s.io
      version: v1
      kind: Ingress
    path: ./patches/ingress-waf-patch.yaml
